connect 'jdbc:derby://localhost:1527/TriveraTunes;create=true;user=sa;password=password';
CREATE TABLE CATEGORY( 
    CATEGORYID INTEGER, 
    NAME VARCHAR(40), 
    CONSTRAINT CATALOGPK PRIMARY KEY ( CATEGORYID )
); 
CREATE TABLE CD(
    ARTNO VARCHAR(20), 
    NAME VARCHAR(60), 
    ARTIST VARCHAR(40), 
    RELEASEDATE DATE, 
    PRICE FLOAT,
    LISTPRICE FLOAT,
    CATEGORYID INTEGER NOT NULL,
    CONSTRAINT CDPK PRIMARY KEY (ARTNO),
    CONSTRAINT CATEGORYFK FOREIGN KEY ( CATEGORYID ) 
    REFERENCES CATEGORY( CATEGORYID )
); 